# Path to SAGPlacer working directory
working_dir: "/home/eherman/scratch/SCG/"
# working_dir: "/path/to/working/directory/"

# Path to directory containing sample files
input: "/home/eherman/scratch/SCG/genomes/"
# input: "/path/to/input/"

# Path to results directory containing all output folders
results: "/home/eherman/scratch/SCG/results/"
# results: "/path/to/results/"

### Program Paths
fastqc: "/home/eherman/scratch/SCG/resources/FastQC/fastqc"
# fastqc: "/path/to/fastqc/binary"
trimmomatic: "/home/eherman/scratch/SCG/resources/Trimmomatic-0.39/trimmomatic-0.39.jar"
# trimmomatic: "/path/to/trimmomatic.jar"
adapters: "/home/eherman/scratch/SCG/resources/Trimmomatic-0.39/adapters/TruSeq-PE-2.fa"
# adapters: "/path/to/Trimmomatic/adapters.fa"
spades: "/home/eherman/scratch/SCG/resources/SPAdes-3.13.1-Linux/bin/spades.py"
# spades: "/path/to/spades.py"
stats: "/home/eherman/soft/assembly-stats/assembly-stats"
# stats: "/path/to/assembly-stats/binary"
bowtie2: "/home/eherman/scratch/SCG/resources/bowtie2-2.3.3.1-linux-x86_64/bowtie2"
# bowtie2: "/path/to/bowtie2/executable"
bowtie2_build: "/home/eherman/scratch/SCG/resources/bowtie2-2.3.3.1-linux-x86_64/bowtie2-build"
# bowtie2_build: "/path/to/bowtie2-build/executable"
samtools: "/home/eherman/scratch/SCG/resources/samtools-1.14/samtools"
# samtools: "/path/to/samtools/executable"
busco: "/home/eherman/scratch/SCG/resources/busco-5.2.1/bin/busco"
# busco: "/path/to/busco/executable"
busco_config: "/home/eherman/scratch/SCG/resources/busco-5.2.1/config/config_mod.ini"
# busco_ini: "/path/to/busco_config.ini"
busco_db: "eukaryota_odb10"
# busco_db: eukaryota_odb10 # (database name)
