# Path to SAGPlacer working directory
#working_dir: "/home/eherman/scratch/SCG/"
working_dir: "/path/to/working/directory/"

# Path to directory containing sample files
#input: "/home/eherman/scratch/SCG/genomes/"
input: "/path/to/input/"

# Path to results directory containing all output folders
#results: "/home/eherman/scratch/SCG/results/"
results: "/path/to/results/"

### Program Paths

# FastQC
#fastqc: "/home/eherman/scratch/SCG/resources/FastQC/fastqc"
fastqc: "/path/to/fastqc/binary"

# Trimmomatic
#trimmomatic: "/home/eherman/scratch/SCG/resources/Trimmomatic-0.39/trimmomatic-0.39.jar"
trimmomatic: "/path/to/trimmomatic.jar"
#adapters: "/home/eherman/scratch/SCG/resources/Trimmomatic-0.39/adapters/TruSeq-PE-2.fa"
adapters: "/path/to/Trimmomatic/adapters.fa"

# SPAdes
#spades: "/home/eherman/scratch/SCG/resources/SPAdes-3.13.1-Linux/bin/spades.py"
spades: "/path/to/spades.py"

# Assembly-Stats
#stats: "/home/eherman/soft/assembly-stats/assembly-stats"
stats: "/path/to/assembly-stats/binary"

# Bowtie2
#bowtie2: "/home/eherman/scratch/SCG/resources/bowtie2-2.3.3.1-linux-x86_64/bowtie2"
bowtie2: "/path/to/bowtie2/executable"
#bowtie2_build: "/home/eherman/scratch/SCG/resources/bowtie2-2.3.3.1-linux-x86_64/bowtie2-build"
bowtie2_build: "/path/to/bowtie2-build/executable"

# Samtools
#samtools: "/home/eherman/scratch/SCG/resources/samtools-1.14/samtools"
samtools: "/path/to/samtools/executable"

# BUSCO
#busco: "/home/eherman/scratch/SCG/resources/busco-5.2.1/bin/busco"
busco: "/path/to/busco/executable"
#busco_config: "/home/eherman/scratch/SCG/resources/busco-5.2.1/config/config_mod.ini"
busco_config: "/path/to/busco_config.ini"
busco_db: "eukaryota_odb10"

# Augustus
augustus: "/path/to/augustus"
#augustus_config: "/home/eherman/scratch/SCG/resources/config/"
augustus_config: "/path/to/augustus/config/directory" # This directory is shipped with the augustus distro and must be writeable
#getannofasta: getAnnoFasta.pl
getannofasta: "/path/to/getAnnoFasta.pl"

# Pannzer
#pannzer: "/home/eherman/scratch/SCG/SANSPANZ.3/runsanspanz.py"
pannzer: "/path/to/runsanspanz.py"